entryPoints:

  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: acmeresolver

api:
  dashboard: true

log:
  level: INFO

providers:

  docker:
    watch: true
    exposedByDefault: false
    swarmMode: true

  file:
    directory: /dynamic
    watch: true

certificatesResolvers:
  acmeresolver:
    acme:
      email: soldat@panacom.cz
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

